### PR TITLE
Landing page update

### PR DESCRIPTION
**Pull request by jinhojang6**
Need to sort out the issue with deployment.

Merged with the master branch but the CSS is broken.

Screen Shot 2022-01-06 at 2 16 12 PM

Looking into this issue with Jakub

### CODE REVIEW

**Comment by oskarth** [comment]
@jinhojang6 let me know if you need anything here from me, from my POV whenever it is ready we can merge it.

**Comment by jinhojang6** [comment]
@oskarth I'm looking into this issue with @jakubgs . Will try to sort this out as soon as possible.

**Comment by jakubgs** [comment]
I temporarily switched the Page build to this branch and the build runs fine:
https://github.com/vacp2p/vacp2p.github.io/runs/4765611133

What fails is the lack of this JS file: https://cdn.simpleanalytics.io/hello.js
image

```
 > curl -sS https://cdn.simpleanalytics.io/hello.js
curl: (7) Failed to connect to cdn.simpleanalytics.io port 443 after 0 ms: Connection refused
```

**Comment by jakubgs** [comment]
Btw, what is https://cdn.simpleanalytics.io/ ? Is this something we asked for?
https://github.com/vacp2p/vacp2p.github.io/blob/1486ff8a3e291b247e78e92699e17fbdd149c487/_includes/head.html#L13-L14
```
 > curl -sS https://cdn.simpleanalytics.io/hello.js | head -n1
/* Simple Analytics - Privacy friendly analytics (docs.simpleanalytics.com/script; 2021-12-30; 79ce) */
```

**Comment by oskarth** [comment]
Looking at current site it seems like we use both Simple Analytics and Fathom.

view-source:https://vac.dev/

I'm not sure what e.g. marketing is using right now? There has been some migration here afaik but forgot details.

**Comment by jakubgs** [comment]
Ok, i see what's happening, the CSS file is not processed:
```
 > curl -sS vac.dev/assets/css/style.css | head
@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: "Open Sans";
  src: url("../../fonts/OpenSans-Regular.woff2") format("woff2"), url("../../fonts/OpenSans-Regular.woff") format("woff");
  font-weight: normal;
  font-style: normal;
  font-display: swap;

```
So the issue is somewhere in that step.

**Comment by jakubgs** [comment]
That should do it. I refactored whole Gulp config. Please review @jinhojang6 .

Essentially the issue was that this was being built with Github Actions for GitHub pages, which by default runs only Jekyll:

image

And we need more than that, we need a full Gulp build. Hence why it will be built on Jenkins, like all our sites.

**Pull request merged**
